name: Metrics
on:
  schedule: [{cron: "0 * * * *"}]
  push: {branches: ["master", "main"]}
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          config_timezone: "Asia/Shanghai"
          repositories: 100
          repositories_forks: yes
          base: "header"
          config_order: "base.header, activity, followup, posts"
          plugin_followup: yes
          plugin_posts: yes
          plugin_posts_source: "dev.to"
          plugin_posts_limit: 4
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 14
          plugin_activity_filter: "all"
